name: Build and Release Tahini Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@v4
        with:
          version: 'latest'
          java-version: '21'

      - name: Install Native Image tool
        run: gu install native-image

      - name: Build jar with Gradle
        run: ./gradlew build

      - name: Compile native image
        run: native-image -jar app/build/libs/tahini.jar tahini

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: tahini-${{ matrix.os }}
          path: tahini*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tahini-ubuntu-latest
            tahini-macos-latest
            tahini-windows-latest.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
